/**
 * OSA Phenotyper – AWS Configuration
 * Auto-generated by deploy.sh on 2026-07-20T16:59:37Z
 * These values are PUBLIC client-side keys — not secrets.
 */
const AWS_CONFIG = {
  region: 'us-east-2',
  userPoolId: 'us-east-2_AFKRixoCn',
  userPoolClientId: '6f7p0fs0m4dqbvpt67qmedhs6u',
  apiUrl: 'https://d3fgk3yvbi0jvr.cloudfront.net',
  appUrl: 'https://d3fgk3yvbi0jvr.cloudfront.net',
  adminGroupName: 'osa-admin',
  clinicianGroupName: 'osa-clinician',
  deploymentEnvironment: 'pilot',
  deploymentLabel: 'CLINICAL PILOT',
  buildId: 'e12734f',
  deployedAt: '2026-07-20T16:59:37Z',
  stackName: 'osa-phenotyper-capital-ent-precision-sleep-pilot',
};
window.AWS_CONFIG = AWS_CONFIG;
