/**
 * OSA Phenotyper – AWS Configuration
 * Auto-generated by deploy.sh on 2026-06-14T11:37:03Z
 * These values are PUBLIC client-side keys — not secrets.
 */
const AWS_CONFIG = {
  region: 'us-east-2',
  userPoolId: 'us-east-2_ohn6HsKt7',
  userPoolClientId: '3im58l76lemm01smregfnk59uc',
  apiUrl: 'https://dk259m1syu2bu.cloudfront.net',
  appUrl: 'https://dk259m1syu2bu.cloudfront.net',
  adminGroupName: 'osa-admin',
  clinicianGroupName: 'osa-clinician',
  deploymentEnvironment: 'staging',
  deploymentLabel: 'STAGING',
  buildId: '027b71a',
  deployedAt: '2026-06-14T11:37:03Z',
  stackName: 'osa-phenotyper-capital-ent-stg-20260401b',
};
window.AWS_CONFIG = AWS_CONFIG;
