#!/bin/bash
#
# OSA Phenotyper – AWS Deployment Script
# Usage: ./deploy.sh <admin-email> [region] [clinic-name] <allowed-origins> [artifact-bucket]
#
# Prerequisites:
#   - AWS CLI installed and configured (aws configure)
#   - BAA signed in AWS Artifact
#   - MFA enabled on root account
#
set -euo pipefail

USAGE="Usage: ./deploy.sh <admin-email> [region] [clinic-name] <allowed-origins> [artifact-bucket]"

ADMIN_EMAIL="${1:?${USAGE}}"
REGION="${2:-us-east-1}"
CLINIC="${3:-capital-ent}"
ALLOWED_ORIGINS="${4:?${USAGE}}"
STACK_NAME="osa-phenotyper-${CLINIC}"
ARTIFACT_BUCKET="${5:-}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATE_FILE="${SCRIPT_DIR}/template.yaml"
PACKAGED_TEMPLATE="/tmp/osa-phenotyper-${CLINIC}-packaged.yaml"

ensure_artifact_bucket_name() {
  if [ -n "${ARTIFACT_BUCKET}" ]; then
    return
  fi
  local account_id
  account_id=$(aws sts get-caller-identity --query Account --output text --region "${REGION}")
  ARTIFACT_BUCKET="osa-phenotyper-artifacts-${CLINIC}-${account_id}-${REGION}"
}

create_artifact_bucket_if_needed() {
  if aws s3api head-bucket --bucket "${ARTIFACT_BUCKET}" >/dev/null 2>&1; then
    echo "  Artifact bucket: ${ARTIFACT_BUCKET}"
    return
  fi

  echo "  Creating artifact bucket: ${ARTIFACT_BUCKET}"
  if [ "${REGION}" = "us-east-1" ]; then
    aws s3api create-bucket \
      --bucket "${ARTIFACT_BUCKET}" \
      --region "${REGION}" > /dev/null
  else
    aws s3api create-bucket \
      --bucket "${ARTIFACT_BUCKET}" \
      --region "${REGION}" \
      --create-bucket-configuration "LocationConstraint=${REGION}" > /dev/null
  fi

  aws s3api put-public-access-block \
    --bucket "${ARTIFACT_BUCKET}" \
    --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true > /dev/null

  aws s3api put-bucket-encryption \
    --bucket "${ARTIFACT_BUCKET}" \
    --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}' > /dev/null
}

echo "═══════════════════════════════════════════════════"
echo "  OSA Phenotyper – Deploying to AWS"
echo "═══════════════════════════════════════════════════"
echo "  Admin email : ${ADMIN_EMAIL}"
echo "  Region      : ${REGION}"
echo "  Clinic      : ${CLINIC}"
echo "  Origins     : ${ALLOWED_ORIGINS}"
echo "  Stack       : ${STACK_NAME}"
ensure_artifact_bucket_name
echo "  Artifacts   : ${ARTIFACT_BUCKET}"
echo "═══════════════════════════════════════════════════"
echo ""

# Step 1: Create/reuse artifact bucket
echo "[1/5] Preparing artifact bucket..."
create_artifact_bucket_if_needed

echo ""
echo "[2/5] Packaging CloudFormation template..."
aws cloudformation package \
  --template-file "${TEMPLATE_FILE}" \
  --s3-bucket "${ARTIFACT_BUCKET}" \
  --output-template-file "${PACKAGED_TEMPLATE}" \
  --region "${REGION}" > /dev/null

echo ""
echo "[3/5] Deploying packaged CloudFormation stack..."
aws cloudformation deploy \
  --template-file "${PACKAGED_TEMPLATE}" \
  --stack-name "${STACK_NAME}" \
  --parameter-overrides \
    ClinicName="${CLINIC}" \
    AdminEmail="${ADMIN_EMAIL}" \
    AllowedOrigins="${ALLOWED_ORIGINS}" \
  --capabilities CAPABILITY_NAMED_IAM \
  --region "${REGION}" \
  --no-fail-on-empty-changeset

echo ""
echo "[4/5] Retrieving configuration..."

# Get outputs
API_URL=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
  --output text)

POOL_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" \
  --output text)

CLIENT_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
  --output text)

ADMIN_GROUP=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='AdminGroup'].OutputValue" \
  --output text)

CLINICIAN_GROUP=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='ClinicianGroup'].OutputValue" \
  --output text)

echo ""
echo "[5/5] Writing runtime configuration..."

# Update aws-config.js
CONFIG_FILE="${SCRIPT_DIR}/../js/aws-config.js"
cat > "${CONFIG_FILE}" << EOF
/**
 * OSA Phenotyper – AWS Configuration
 * Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
 * These values are PUBLIC client-side keys — not secrets.
 */
const AWS_CONFIG = {
  region: '${REGION}',
  userPoolId: '${POOL_ID}',
  userPoolClientId: '${CLIENT_ID}',
  apiUrl: '${API_URL}',
  adminGroupName: '${ADMIN_GROUP}',
  clinicianGroupName: '${CLINICIAN_GROUP}',
};
EOF

# Update intake page runtime URL + CSP connect-src origin
INTAKE_FILE="${SCRIPT_DIR}/../intake.html"
perl -0pi -e "s#(<meta http-equiv=\"Content-Security-Policy\" content=\"[^\"]*connect-src )[^;]+#\${1}'self' ${API_URL}#g" "${INTAKE_FILE}"
perl -0pi -e "s#data-api-url=\"[^\"]*\"#data-api-url=\"${API_URL}\"#g" "${INTAKE_FILE}"
echo ""
echo "═══════════════════════════════════════════════════"
echo "  Deployment complete!"
echo "═══════════════════════════════════════════════════"
echo ""
echo "  API URL      : ${API_URL}"
echo "  User Pool    : ${POOL_ID}"
echo "  Client ID    : ${CLIENT_ID}"
echo "  Allowed CORS : ${ALLOWED_ORIGINS}"
echo "  Artifacts    : ${ARTIFACT_BUCKET}"
echo "  Intake page  : Served from your web server at /intake.html"
echo ""
echo "  Config written to: js/aws-config.js"
echo ""
echo "  A temporary password has been sent to: ${ADMIN_EMAIL}"
echo "  Use it to sign in — you'll be prompted to set a new password and configure MFA."
echo ""
echo "  Next steps:"
echo "  1. Open the app in your browser"
echo "  2. Sign in with your email and the temporary password"
echo "  3. Set your new password"
echo "  4. Start adding patients!"
echo ""

# Cleanup
rm -f "${PACKAGED_TEMPLATE}"
