#!/bin/bash
#
# OSA Phenotyper – AWS Deployment Script
# Usage: ./deploy.sh <admin-email> [region] [clinic-name] <allowed-origins>
#
# Prerequisites:
#   - AWS CLI installed and configured (aws configure)
#   - BAA signed in AWS Artifact
#   - MFA enabled on root account
#
set -euo pipefail

USAGE="Usage: ./deploy.sh <admin-email> [region] [clinic-name] <allowed-origins>"

ADMIN_EMAIL="${1:?${USAGE}}"
REGION="${2:-us-east-1}"
CLINIC="${3:-capital-ent}"
ALLOWED_ORIGINS="${4:?${USAGE}}"
STACK_NAME="osa-phenotyper-${CLINIC}"

echo "═══════════════════════════════════════════════════"
echo "  OSA Phenotyper – Deploying to AWS"
echo "═══════════════════════════════════════════════════"
echo "  Admin email : ${ADMIN_EMAIL}"
echo "  Region      : ${REGION}"
echo "  Clinic      : ${CLINIC}"
echo "  Origins     : ${ALLOWED_ORIGINS}"
echo "  Stack       : ${STACK_NAME}"
echo "═══════════════════════════════════════════════════"
echo ""

# Step 1: Deploy CloudFormation stack
echo "[1/4] Deploying CloudFormation stack..."
aws cloudformation deploy \
  --template-file "$(dirname "$0")/template.yaml" \
  --stack-name "${STACK_NAME}" \
  --parameter-overrides \
    ClinicName="${CLINIC}" \
    AdminEmail="${ADMIN_EMAIL}" \
    AllowedOrigins="${ALLOWED_ORIGINS}" \
  --capabilities CAPABILITY_NAMED_IAM \
  --region "${REGION}" \
  --no-fail-on-empty-changeset

echo ""
echo "[2/4] Deploying Lambda function code..."

# Package and deploy Lambdas
LAMBDA_DIR="$(dirname "$0")/lambda"
LAMBDA_ZIP="/tmp/osa-lambda-${CLINIC}.zip"
INTAKE_ZIP="/tmp/osa-intake-lambda-${CLINIC}.zip"
FUNCTION_NAME="osa-patients-api-${CLINIC}"
INTAKE_FUNCTION_NAME="osa-intake-api-${CLINIC}"

# Create and deploy main Lambda
(cd "${LAMBDA_DIR}" && zip -r "${LAMBDA_ZIP}" index.mjs)
aws lambda update-function-code \
  --function-name "${FUNCTION_NAME}" \
  --zip-file "fileb://${LAMBDA_ZIP}" \
  --region "${REGION}" > /dev/null

echo ""
echo "[3/4] Deploying Intake Lambda function code..."

# Create and deploy intake Lambda
(cd "${LAMBDA_DIR}" && zip -r "${INTAKE_ZIP}" intake.mjs)
aws lambda update-function-code \
  --function-name "${INTAKE_FUNCTION_NAME}" \
  --zip-file "fileb://${INTAKE_ZIP}" \
  --region "${REGION}" > /dev/null

echo ""
echo "[4/4] Retrieving configuration..."

# Get outputs
API_URL=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
  --output text)

POOL_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" \
  --output text)

CLIENT_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
  --output text)

ADMIN_GROUP=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='AdminGroup'].OutputValue" \
  --output text)

CLINICIAN_GROUP=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='ClinicianGroup'].OutputValue" \
  --output text)

# Update aws-config.js
CONFIG_FILE="$(dirname "$0")/../js/aws-config.js"
cat > "${CONFIG_FILE}" << EOF
/**
 * OSA Phenotyper – AWS Configuration
 * Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
 * These values are PUBLIC client-side keys — not secrets.
 */
const AWS_CONFIG = {
  region: '${REGION}',
  userPoolId: '${POOL_ID}',
  userPoolClientId: '${CLIENT_ID}',
  apiUrl: '${API_URL}',
  adminGroupName: '${ADMIN_GROUP}',
  clinicianGroupName: '${CLINICIAN_GROUP}',
};
EOF

# Update intake page runtime URL + CSP connect-src origin
INTAKE_FILE="$(dirname "$0")/../intake.html"
perl -0pi -e "s#(<meta http-equiv=\"Content-Security-Policy\" content=\"[^\"]*connect-src )[^;]+#\${1}'self' ${API_URL}#g" "${INTAKE_FILE}"
perl -0pi -e "s#data-api-url=\"[^\"]*\"#data-api-url=\"${API_URL}\"#g" "${INTAKE_FILE}"

echo ""
echo "═══════════════════════════════════════════════════"
echo "  Deployment complete!"
echo "═══════════════════════════════════════════════════"
echo ""
echo "  API URL      : ${API_URL}"
echo "  User Pool    : ${POOL_ID}"
echo "  Client ID    : ${CLIENT_ID}"
echo "  Allowed CORS : ${ALLOWED_ORIGINS}"
echo "  Intake page  : Served from your web server at /intake.html"
echo ""
echo "  Config written to: js/aws-config.js"
echo ""
echo "  A temporary password has been sent to: ${ADMIN_EMAIL}"
echo "  Use it to sign in — you'll be prompted to set a new password and configure MFA."
echo ""
echo "  Next steps:"
echo "  1. Open the app in your browser"
echo "  2. Sign in with your email and the temporary password"
echo "  3. Set your new password"
echo "  4. Start adding patients!"
echo ""

# Cleanup
rm -f "${LAMBDA_ZIP}" "${INTAKE_ZIP}"
