#!/bin/bash
#
# OSA Phenotyper – AWS Deployment Script
# Usage: ./deploy.sh <admin-email> [region] [clinic-name]
#
# Prerequisites:
#   - AWS CLI installed and configured (aws configure)
#   - BAA signed in AWS Artifact
#   - MFA enabled on root account
#
set -euo pipefail

ADMIN_EMAIL="${1:?Usage: ./deploy.sh <admin-email> [region] [clinic-name]}"
REGION="${2:-us-east-1}"
CLINIC="${3:-capital-ent}"
STACK_NAME="osa-phenotyper-${CLINIC}"

echo "═══════════════════════════════════════════════════"
echo "  OSA Phenotyper – Deploying to AWS"
echo "═══════════════════════════════════════════════════"
echo "  Admin email : ${ADMIN_EMAIL}"
echo "  Region      : ${REGION}"
echo "  Clinic      : ${CLINIC}"
echo "  Stack       : ${STACK_NAME}"
echo "═══════════════════════════════════════════════════"
echo ""

# Step 1: Deploy CloudFormation stack
echo "[1/4] Deploying CloudFormation stack..."
aws cloudformation deploy \
  --template-file "$(dirname "$0")/template.yaml" \
  --stack-name "${STACK_NAME}" \
  --parameter-overrides \
    ClinicName="${CLINIC}" \
    AdminEmail="${ADMIN_EMAIL}" \
  --capabilities CAPABILITY_NAMED_IAM \
  --region "${REGION}" \
  --no-fail-on-empty-changeset

echo ""
echo "[2/4] Deploying Lambda function code..."

# Package and deploy Lambdas
LAMBDA_DIR="$(dirname "$0")/lambda"
LAMBDA_ZIP="/tmp/osa-lambda-${CLINIC}.zip"
INTAKE_ZIP="/tmp/osa-intake-lambda-${CLINIC}.zip"
FUNCTION_NAME="osa-patients-api-${CLINIC}"
INTAKE_FUNCTION_NAME="osa-intake-api-${CLINIC}"

# Create and deploy main Lambda
(cd "${LAMBDA_DIR}" && zip -r "${LAMBDA_ZIP}" index.mjs)
aws lambda update-function-code \
  --function-name "${FUNCTION_NAME}" \
  --zip-file "fileb://${LAMBDA_ZIP}" \
  --region "${REGION}" > /dev/null

echo ""
echo "[3/4] Deploying Intake Lambda function code..."

# Create and deploy intake Lambda
(cd "${LAMBDA_DIR}" && zip -r "${INTAKE_ZIP}" intake.mjs)
aws lambda update-function-code \
  --function-name "${INTAKE_FUNCTION_NAME}" \
  --zip-file "fileb://${INTAKE_ZIP}" \
  --region "${REGION}" > /dev/null

echo ""
echo "[4/4] Retrieving configuration..."

# Get outputs
API_URL=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
  --output text)

POOL_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolId'].OutputValue" \
  --output text)

CLIENT_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='UserPoolClientId'].OutputValue" \
  --output text)

# Update aws-config.js
CONFIG_FILE="$(dirname "$0")/../js/aws-config.js"
cat > "${CONFIG_FILE}" << EOF
/**
 * OSA Phenotyper – AWS Configuration
 * Auto-generated by deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
 * These values are PUBLIC client-side keys — not secrets.
 */
const AWS_CONFIG = {
  region: '${REGION}',
  userPoolId: '${POOL_ID}',
  userPoolClientId: '${CLIENT_ID}',
  apiUrl: '${API_URL}',
};
EOF

# Associate WAF with API Gateway (if WAF exists)
WAF_ARN=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='WafWebAclArn'].OutputValue" \
  --output text 2>/dev/null || echo "")

API_ID=$(aws cloudformation describe-stacks \
  --stack-name "${STACK_NAME}" \
  --region "${REGION}" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiId'].OutputValue" \
  --output text 2>/dev/null || echo "")
API_STAGE_ARN="arn:aws:apigateway:${REGION}::/apis/${API_ID}/stages/\$default"

if [ -n "${WAF_ARN}" ] && [ "${WAF_ARN}" != "None" ]; then
  echo "Associating WAF with API Gateway..."
  aws wafv2 associate-web-acl \
    --web-acl-arn "${WAF_ARN}" \
    --resource-arn "${API_STAGE_ARN}" \
    --region "${REGION}" 2>/dev/null || echo "  (WAF association skipped — may require manual setup)"
fi

echo ""
echo "═══════════════════════════════════════════════════"
echo "  Deployment complete!"
echo "═══════════════════════════════════════════════════"
echo ""
echo "  API URL      : ${API_URL}"
echo "  User Pool    : ${POOL_ID}"
echo "  Client ID    : ${CLIENT_ID}"
echo "  Intake page  : Served from your web server at /intake.html"
echo ""
echo "  Config written to: js/aws-config.js"
echo ""
echo "  A temporary password has been sent to: ${ADMIN_EMAIL}"
echo "  Use it to sign in — you'll be prompted to set a new password."
echo ""
echo "  Next steps:"
echo "  1. Open the app in your browser"
echo "  2. Sign in with your email and the temporary password"
echo "  3. Set your new password"
echo "  4. Start adding patients!"
echo ""

# Cleanup
rm -f "${LAMBDA_ZIP}" "${INTAKE_ZIP}"
